package com.websystique.springmvc.dao;

import com.websystique.springmvc.model.TblCompany;
import com.websystique.springmvc.model.TblCompanyExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TblCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMPANY
     *
     * @mbggenerated
     */
    int countByExample(TblCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMPANY
     *
     * @mbggenerated
     */
    int deleteByExample(TblCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMPANY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMPANY
     *
     * @mbggenerated
     */
    int insert(TblCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMPANY
     *
     * @mbggenerated
     */
    int insertSelective(TblCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMPANY
     *
     * @mbggenerated
     */
    List<TblCompany> selectByExample(TblCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMPANY
     *
     * @mbggenerated
     */
    TblCompany selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMPANY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblCompany record, @Param("example") TblCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMPANY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblCompany record, @Param("example") TblCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMPANY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMPANY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblCompany record);
}