package com.websystique.springmvc.dao;

import com.websystique.springmvc.model.TblUser;
import com.websystique.springmvc.model.TblUserExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TblUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbggenerated
     */
    int countByExample(TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbggenerated
     */
    int deleteByExample(TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbggenerated
     */
    int insert(TblUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbggenerated
     */
    int insertSelective(TblUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbggenerated
     */
    List<TblUser> selectByExample(TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbggenerated
     */
    TblUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblUser record, @Param("example") TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblUser record, @Param("example") TblUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblUser record);
}