package com.websystique.springmvc.model;

public class TblCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COMPANY.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COMPANY.COMPANY_NAME
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COMPANY.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COMPANY.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COMPANY.TELPHONE
     *
     * @mbggenerated
     */
    private String telphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_COMPANY.ID
     *
     * @return the value of TBL_COMPANY.ID
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_COMPANY.ID
     *
     * @param id the value for TBL_COMPANY.ID
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_COMPANY.COMPANY_NAME
     *
     * @return the value of TBL_COMPANY.COMPANY_NAME
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_COMPANY.COMPANY_NAME
     *
     * @param companyName the value for TBL_COMPANY.COMPANY_NAME
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_COMPANY.ADDRESS
     *
     * @return the value of TBL_COMPANY.ADDRESS
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_COMPANY.ADDRESS
     *
     * @param address the value for TBL_COMPANY.ADDRESS
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_COMPANY.EMAIL
     *
     * @return the value of TBL_COMPANY.EMAIL
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_COMPANY.EMAIL
     *
     * @param email the value for TBL_COMPANY.EMAIL
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_COMPANY.TELPHONE
     *
     * @return the value of TBL_COMPANY.TELPHONE
     * @mbggenerated
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_COMPANY.TELPHONE
     *
     * @param telphone the value for TBL_COMPANY.TELPHONE
     * @mbggenerated
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }
}